version: '3'

###just adeded
networks:
  mynetwork:
    ipam:
      config:
        - subnet: 192.168.3.0/24
###


services:

  victim:
    image: victim
    container_name: victim
    build: ./victim
    stdin_open: true
    tty: true
    volumes:
      - ./email/attacker/sent:/home/victim/email/inbox
      - ./email/victim/sent:/home/victim/email/sent
      - ./victim/Downloads:/home/victim/app
      #- ./victim/Backup:/mnt/backupDrive
    networks:
      mynetwork:
        ipv4_address: 192.168.3.4
    ports:
      - "5001:5001"
    depends_on:
      - attacker
  
  attacker:
    image: attacker
    container_name: attacker
    build: ./attacker
    stdin_open: true
    tty: true
    volumes:
      - ./email/victim/sent:/home/attacker/email/inbox
      - ./email/attacker/sent:/home/attacker/email/sent
    networks:
      mynetwork:
        ipv4_address: 192.168.3.3
    ports:
      - "5002:5001"
    depends_on:
      - homework-hero
  


  homework-hero:
    image: homework-hero
  #  depends_on:
  #      - vue-example
    container_name: attacker_homework-hero
    build:
      target: development
      context: ./hwHero
   # volumes:
   #   - ./src:/app/src
    ports:
      - 3000:3000



      